ORG 0000H
MOV R0, #31H
MOV A, R0
MOV B, R0
MUL AB ;SQUARE
MOV R1, B ;MOVE HIGHER BYTE TO R1 (A-LWB, B-UPB)
MOV B, R0 ;MOVE 13H TO B
MUL AB ;CUBE PART1
MOV R5, A ;MOVE LOWER BYTE RESULT TO R5
MOV R2, B; MOVE HIGHER BYTE TO R2
MOV A, R1 ;MOVE FORMER HIGHER BYTE TO A
MOV B, R0 ;MOVE 13H TO B
MUL AB ;CUBE PART2
MOV R7, B ;MOVE HIGHER BYTE RESULT TO R7
MOV R3, A 
MOV A, R2
MOV B, R3
ADD A, B
MOV R6, A
JC IFCARRY
SJMP END
IFCARRY:
INC R7
END:
END
