; P2. Write an assembly language program to find whether the given number is prime or not. If
; prime send FFh to Port 0 else send 00h to Port 0.
ORG 0000H
MOV R1, #08H ;INPUT
MOV R2, #02H ;FIRST DIVIDER
MOV R3, #0H ;CHECKER
MOV A, R1 ;IMOVE SI INPUT
MOV B, R2 ;IMOVE SI FIRST DIVIDER
DIV AB ; A=QUOTIENT, B=REMAINDER
MOV R4, A ; MOVE SI QUOTIENT SA R4
LOOP:
MOV A, R1 ;IMOVE SI INPUT
MOV B, R2 ;IMOVE SI FIRST DIVIDER
DIV AB ; A=QUOTIENT, B=REMAINDER
MOV R5, A ; MOVE SI QUOTIENT SA R4
MOV A, B ; A = REMAINDER NA
MOV B, R3 ; B = 0H = CHECKER
CJNE A, B, NEXT ; A>=B C=0, A<B C=1
MOV P0, #00H
MOV R7, P0
SJMP LAST
NEXT:
INC R2
DJNZ R4, LOOP
MOV P0, #0FFH
MOV R7, P0
LAST:
END